# inspired by 
# http://sebgoa.blogspot.com/2015/03/1-command-to-mesos-with-docker-compose.html

mesosmaster:
  image: mesosphere/mesos-master:${MESOS_VERSION}
  ports:
    - "5050:5050"
  links:
    - zookeeper:zk
  environment:
    - MESOS_ZK=zk://zk:2181/mesos
    - MESOS_QUORUM=1
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_CLUSTER=Local Cluster

mesosslave:
  image: mesosphere/mesos-slave:${MESOS_VERSION}
  ports:
    - "5051:5051"
  privileged: true
  links:
    - zookeeper:zk
    - mesosmaster:master
  environment:
    - MESOS_MASTER=zk://zk:2181/mesos
    - MESOS_WORK_DIR=/var/lib/mesos
    - MESOS_LOGGING_LEVEL=INFO

zookeeper:
  build: zk
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"

marathon:
  image: mesosphere/marathon:${MARATHON_VERSION}
  ports:
    - "8080:8080"
  links:
    - zookeeper:zk
    - mesosmaster:master
  environment:
    - MARATHON_MASTER=zk://zk:2181/mesos
    - MARATHON_ZK=zk://zk:2181/marathon

